import = ["~/.config/alacritty/common.toml"]

[env]
TERM = "xterm-256color"

[colors.cursor]
cursor = "#e7dbb7"
text = "#1f1f1f"

[colors.primary]
background = "#2c2e34"
foreground = "#c5c8c6"

[font]
size = 13.5

[font.normal]
style = "Regular"

[window.dimensions]
columns = 113
lines = 39
