cursor_blink_interval 0
allow_remote_control yes
listen_on unix:/tmp/mykitty

# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMonoNL Nerd Font Mono' postscript_name=JetBrainsMonoNLNFM-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# font_features none
# END_KITTY_FONTS

include ${KITTY_OS}.conf
# placement_strategy top-left
enabled_layouts splits,stack

tab_bar_style fade
# fade 默认加粗斜体，normal 去掉斜体
active_tab_font_style normal
tab_bar_edge top
tab_bar_background #2D2E33
active_tab_foreground #F0F0F1
active_tab_background #626366
inactive_tab_foreground #A9AAAC
inactive_tab_background #48494C

# tab_bar_style custom
# tab_title_max_length 8
# # tab_bar.py uses this value as both max and min (fixed width)
# tab_bar_min_tabs 1
# hide_window_decorations titlebar-only

pixel_scroll yes
momentum_scroll 0.96

# cursor_trail 1
# cursor_trail_decay 0 0.3

macos_titlebar_color dark

window_margin_width 0

include ~/.dotfiles/kitty/gruvbox_dark.conf

remember_window_size  no

initial_window_width  1021
initial_window_height 816

mouse_hide_wait 3.0

# map ctrl+home resize_window reset
map command+n send_text all \033n
map shift+command+t new_os_window
map ctrl+b>ctrl+b send_text all \x02
map ctrl+b>c new_tab
map alt+t new_tab_with_cwd
map ctrl+b>x close_window
map ctrl+b>n next_tab
map ctrl+b>ctrl+n next_tab
map ctrl+b>p previous_tab
map ctrl+b>ctrl+p previous_tab
map ctrl+b>w combine : kitten tabpick_collect.py : kitten tabpick.py
map ctrl+b>1 goto_tab 1
map ctrl+b>2 goto_tab 2
map ctrl+b>3 goto_tab 3
map ctrl+b>4 goto_tab 4
map ctrl+b>5 goto_tab 5
map ctrl+b>6 goto_tab 6
map ctrl+b>7 goto_tab 7
map ctrl+b>8 goto_tab 8
map ctrl+b>9 goto_tab 9
map ctrl+b>o next_window
map ctrl+b>ctrl+o next_window
map ctrl+b>u move_window_forward
map ctrl+b>shift+u swap_with_window
map ctrl+b>q detach_window new-tab
map ctrl+b>shift+q detach_window
map ctrl+b>r load_config_file

map ctrl+b>% launch --location=split --cwd=current
map ctrl+b>m detach_window ask
map ctrl+b>h kitten hints --type path --alphabet qfjdkslaureitywovmcxzpq --program "-"
map ctrl+b>shift+h goto_tab 1
map ctrl+b>shift+l goto_tab -1

# osc52 读取clipboard无需确认
clipboard_control write-clipboard write-primary read-clipboard read-primary
