-- local M = {}
--
-- local view = require('nvim-tree.view')
-- local filetree = require('lu5je0.core.filetree')
--
-- local function hijack_directory(path)
--   if vim.fn.exists(path) and not vim.fn.isdirectory(path) then
--     return
--   end
--   
--   if not view.is_visible() then
--     vim.defer_fn(function()
--       local dir_bufnr = vim.api.nvim_get_current_buf()
--       vim.cmd('NvimTreeOpen' .. vim.fn.fnameescape(path))
--       vim.cmd("silent! bd! " .. dir_bufnr)
--     end, 1)
--   else
--     filetree.open_path(path)
--   end
-- end
--
-- function M.setup()
--   local group = vim.api.nvim_create_augroup('nvim-tree-hijack', { clear = true })
--   vim.api.nvim_create_autocmd('BufEnter', {
--     group = group,
--     pattern = { '*' },
--     callback = function(arg)
--       if arg.file == '' then
--         return
--       end
--       hijack_directory(arg.file)
--     end
--   })
-- end
--
-- return M
