local M = {}

function M.opts()
  return {
    preset = 'classic',
    delay = 1000,
    plugins = {
      marks = true,
      registers = true,
      presets = {
        operators = false,
        motions = false,
        text_objects = false,
        windows = true,
        nav = false,
        z = true,
        g = false,
      },
      spelling = { enabled = true, suggestions = 20 },
    },
    icons = {
      breadcrumb = '»',
      separator = '➜',
      group = '+',
      rules = {
        { pattern = '^lazy$', icon = '󰒲 ', color = 'yellow' },
        { pattern = '^run$', icon = '󰜎 ', color = 'green' },
        { pattern = '^vim$', icon = ' ', color = 'green' },
        { pattern = '^text$', icon = '󰉿 ', color = 'blue' },
        { pattern = 'symbol', icon = '󰘦 ', color = 'blue' },
        { pattern = 'translate', icon = '󰗊 ', color = 'cyan' },
        { pattern = 'project', icon = '󱂬 ', color = 'green' },
        { pattern = 'mru', icon = '󱋡 ', color = 'yellow' },
        { pattern = 'register', icon = '󰘓 ', color = 'orange' },
        { pattern = 'undotree', icon = ' ', color = 'purple' },
        { pattern = 'highlight', icon = '󱥚 ', color = 'yellow' },
        { pattern = 'mark', icon = '󰃀 ', color = 'orange' },
        { pattern = 'gist', icon = ' ', color = 'grey' },
        { pattern = 'blame', icon = '󰊢 ', color = 'orange' },
        { pattern = 'hunk', icon = '󰦓 ', color = 'green' },
        { pattern = 'diff', icon = '󰦒 ', color = 'blue' },
        { pattern = 'write', icon = ' ', color = 'azure' },
        { pattern = 'encoding', icon = '󰉿 ', color = 'cyan' },
        { pattern = 'unicode', icon = '󰌆 ', color = 'purple' },
        { pattern = 'replace', icon = '󰛔 ', color = 'blue' },
        { pattern = 'calculator', icon = '󰃬 ', color = 'orange' },
        { pattern = 'calcultor', icon = '󰃬 ', color = 'orange' },
        { pattern = 'workspace', icon = '󱂬 ', color = 'green' },
        { pattern = 'lazygit', icon = '󰊢 ', color = 'red' },
        { pattern = 'time%-machine', icon = '󰔚 ', color = 'cyan' },
      },
    },
    win = {
      border = 'none',
      padding = { 1, 2 },
      title = false,
    },
    layout = {
      width = { min = 20, max = 80 },
      spacing = 2,
    },
    triggers = {
      { '<leader>', mode = { 'n', 'x' } },
      { '<space>',  mode = { 'n', 'x' } },
      { '<c-w>',    mode = 'n' },
      { 'z',        mode = 'n' },
    },
    show_help = true,
    spec = {
      { '<leader>0', desc = 'pick buffer' },
      { '<leader>1', hidden = true },
      { '<leader>2', hidden = true },
      { '<leader>3', hidden = true },
      { '<leader>4', hidden = true },
      { '<leader>5', hidden = true },
      { '<leader>6', hidden = true },
      { '<leader>7', hidden = true },
      { '<leader>8', hidden = true },
      { '<leader>9', hidden = true },
      { '<leader>/', desc = 'eregex toggle' },
      { '<leader>,', desc = 'last buffer' },
      { '<leader>A', desc = 'calcultor and replace' },
      { '<leader>E', desc = 'focus file explorer' },
      { '<leader>I', desc = 'focus symbols' },
      { '<leader>Q', desc = 'exit' },
      { '<leader>a', desc = 'calcultor', mode = { 'n', 'x' } },
      { '<leader>e', desc = 'file explorer' },
      { '<leader>i', desc = 'symbols' },
      { '<leader>n', '<cmd>noh<cr>', desc = 'no highlight' },
      { '<leader>q', desc = 'close buffer' },
      { '<leader>r', group = 'run' },
      { '<leader>rr', desc = 'run' },
      { '<leader>rd', desc = 'debug' },
      { '<leader>rx', desc = 'stop' },
      { '<leader>s', desc = 'symbols' },
      { '<leader>u', desc = 'undotree' },
      { '<leader>v', group = 'vim' },
      { '<leader>vs', desc = 'toggle signcolumn' },
      { '<leader>vS', '<cmd>set signcolumn=yes | echo "set signcolumn=yes"<cr>', desc = 'set signcolumn=yes' },
      { '<leader>vi', desc = 'toggle-save-last-ime' },
      { '<leader>vv', function() vim.cmd('edit ' ..
        vim.env.HOME .. '/.dotfiles/vim/init.lua | cd ' .. vim.env.HOME .. '/.dotfiles/vim') end, desc = 'edit init.lua' },
      { '<leader>W', group = 'workspace' },
      { '<leader>w', group = 'windows', mode = { 'n', 'x' } },
      { '<leader>wn', '<cmd>vnew<cr>', desc = 'vnew' },
      { '<leader>wN', '<cmd>new<cr>', desc = 'new' },
      { '<leader>wo', desc = 'hide other windows' },
      { '<leader>wp', '<cmd>BufferLinePick<cr>', desc = 'buffer pick' },
      { '<leader>wq', '<cmd>only<cr>', desc = 'break window' },
      { '<leader>wr', desc = 'translate and replace', mode = { 'n', 'x' } },
      { '<leader>ws', '<cmd>vsplit<cr>', desc = 'vspilt' },
      { '<leader>wS', '<cmd>split<cr>', desc = 'spilt' },
      { '<leader>wu', '<c-w>x', desc = 'buffer pick' },
      { '<leader>ww', desc = 'translate', mode = { 'n', 'x' } },
      { '<leader>wm', '<cmd>BufferLinePickSplit<cr>', desc = 'spilit with' },

      { '<leader>p', group = 'lazy' },
      { '<leader>pc', '<cmd>Lazy check<cr>', desc = 'check update' },
      { '<leader>pp', desc = 'profile.nvim' },
      { '<leader>ps', desc = 'snacks profile' },

      { '<leader>m', group = 'mark', mode = { 'n', 'x' } },
      { '<leader>mb', desc = 'marked in brown', mode = 'x' },
      { '<leader>mc', desc = 'clear color', mode = { 'n', 'x' } },
      { '<leader>mg', desc = 'marked in green', mode = 'x' },
      { '<leader>mr', desc = 'marked in red', mode = 'x' },
      { '<leader>my', desc = 'marked in yellow', mode = 'x' },

      { '<leader>c', group = 'code', mode = { 'n', 'x' } },
      { '<leader>cc', desc = 'code-action' },
      { '<leader>cf', desc = 'code-formatting', mode = { 'n', 'x' } },
      { '<leader>cn', group = 'naming case', mode = { 'n', 'x' } },
      { '<leader>cnc', desc = 'camelCase', mode = { 'n', 'x' } },
      { '<leader>cnC', desc = 'camelCase(WORD)' },
      { '<leader>cnk', desc = 'kebab-case', mode = { 'n', 'x' } },
      { '<leader>cnK', desc = 'kebab-case(WORD)' },
      { '<leader>cnp', desc = 'PascalCase', mode = { 'n', 'x' } },
      { '<leader>cnP', desc = 'PascalCase(WORD)' },
      { '<leader>cns', desc = 'snake_case', mode = { 'n', 'x' } },
      { '<leader>cnS', desc = 'snake_case(WORD)' },
      { '<leader>cr', desc = 'rename-variable' },

      { '<leader>t', group = 'tab' },
      { '<leader>tc', '<cmd>tabclose<cr>', desc = 'close-tab' },
      { '<leader>th', desc = 'close-to-left' },
      { '<leader>tl', desc = 'close-to-right' },
      { '<leader>tn', '<cmd>enew<cr>', desc = 'new-buffer' },
      { '<leader>tN', '<cmd>tabnew<cr>', desc = 'new-tab' },
      { '<leader>to', desc = 'close-other-buffers' },

      { '<leader>f', group = 'search/files', mode = { 'n', 'x' } },
      { '<leader>f"', desc = 'register' },
      { '<leader>fC', desc = 'colorscheme' },
      { '<leader>fG', desc = 'git-diff' },
      { '<leader>fJ', '<cmd>JunkFileSaveAs<cr>', desc = 'new-junk-file' },
      { '<leader>fR', desc = 'fuzzy search' },
      { '<leader>fW', '<cmd>SudaWrite<cr>', desc = 'sudo-write' },
      { '<leader>fb', desc = 'buffer' },
      { '<leader>fc', desc = 'commnad' },
      { '<leader>fe', desc = 'locate-file' },
      { '<leader>ff', desc = 'file', mode = { 'n', 'x' } },
      { '<leader>fg', desc = 'git-changes' },
      { '<leader>fh', desc = 'help' },
      { '<leader>fj', desc = 'junk-list' },
      { '<leader>fl', desc = 'line' },
      { '<leader>fm', desc = 'mru' },
      { '<leader>fn', desc = 'filetype' },
      { '<leader>fp', desc = 'projects' },
      { '<leader>fr', desc = 'regex search', mode = { 'n', 'x' } },
      { '<leader>fs', desc = 'symbols' },
      { '<leader>ft', desc = 'time-machine' },
      { '<leader>fw', require('lu5je0.core.file').save_buffer, desc = 'write' },
      { '<leader>fx', group = 'encoding' },
      { '<leader>fxa', '<cmd>set ff=unix<cr>', desc = '2unix' },
      { '<leader>fxb', '<cmd>set ff=dos<cr>', desc = '2dos' },
      { '<leader>fxg', '<cmd>set fileencoding=GB18030<cr>', desc = 'convert to gb18030' },
      { '<leader>fxu', '<cmd>set fileencoding=utf8<cr>', desc = 'convert to utf8' },

      { '<leader>x', group = 'text', mode = { 'n', 'x' } },
      { '<leader>xc', 'g<c-g>', desc = 'count in the selection region', mode = 'x' },
      { '<leader>xf', desc = 'replace in current file' },
      { '<leader>xh', desc = 'url encode' },
      { '<leader>xH', desc = 'url decode' },
      { '<leader>xm', [[:%s/\r$//<cr>]], desc = 'remove ^M' },
      { '<leader>xr', desc = 'replace word', mode = { 'n', 'x' } },
      { '<leader>xs', desc = 'text escape', mode = 'x' },
      { '<leader>xu', desc = 'escape unicode' },
      { '<leader>xU', desc = 'unescape unicode' },
      { '<leader>xx', desc = ':%!', mode = { 'n', 'x' } },
      { '<leader>xz', desc = '繁体转简体' },
      { '<leader>xZ', desc = '简体转繁体' },

      { '<leader>g', group = 'git', mode = { 'n', 'x' } },
      { '<leader>gA', '<cmd>Git add -A<cr>', desc = 'add all' },
      { '<leader>gC', '<cmd>Gread<cr>', desc = 'git checkout -- current file' },
      { '<leader>gD', '<cmd>Git diff --cached<cr>', desc = 'diff --cached' },
      { '<leader>gL', desc = 'show changes on current file', mode = { 'n', 'x' } },
      { '<leader>go', desc = 'lazygit' },
      { '<leader>ga', desc = 'stage buffer', mode = { 'n', 'x' } },
      { '<leader>gb', desc = 'blame' },
      { '<leader>gd', '<cmd>Git diff<cr>', desc = 'diff' },
      { '<leader>gg', desc = 'preview hunk' },
      { '<leader>gh', desc = 'stage hunk' },
      { '<leader>gl', '<cmd>Flogsplit<cr>', desc = 'git log in repository', mode = { 'n' } },
      { '<leader>gs', '<cmd>Floggit<cr>', desc = 'Floggit' },
      { '<leader>gr', desc = 'unstage buffer', mode = { 'n', 'x' } },
      { '<leader>gu', desc = 'reset hunk', mode = { 'n', 'x' } },
      { '<leader>gv', '<cmd>Gvdiffsplit!<cr>', desc = 'gvdiffsplit' },
    },
  }
end

function M.setup(opts)
  require('which-key').setup(opts or M.opts())
end

return M
