set nocompatible               "去除VIM一致性，必须
filetype off                   "必须

" 设置包括vundle和初始化相关的运行时路径
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" 启用vundle管理插件，必须
Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-airline'

" 在此增加其他插件，安装的插件需要放在vundle#begin和vundle#end之间
" 安装github上的插件格式为 Plugin '用户名/插件仓库名'

call vundle#end()              
filetype plugin indent on      "加载vim自带和插件相应的语法和文件类型相关脚本，必须"

" airline
set t_Co=256
set laststatus=2
set ambiwidth=double
let g:airline_powerline_fonts=1

let g:airline_left_sep = ''
let g:airline_left_sep = ''
let g:airline_right_sep = ''
let g:airline_right_sep = ''

" 搜索设置
" 高亮搜索结果
set hlsearch
" 搜索时忽略大小写
set ignorecase
" 每输入一个字符就跳转到对应的结果
set incsearch

" 关闭错误响声
set noerrorbells

set autoindent
set number
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4
set encoding=utf8 
set fileencoding=utf-8 
set fileencodings=ucs-bom,utf-8,utf-16,gbk,big5,gb18030,latin1
syntax on
