#ifndef TUI_BRIDGE_STATUS_H
#define TUI_BRIDGE_STATUS_H

#define BRIDGE_STATUS_OK 0
#define BRIDGE_STATUS_INVALID_METHOD 1
#define BRIDGE_STATUS_INVALID_PARAMS 2
#define BRIDGE_STATUS_FAILED 3

#endif
