/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 35
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 43
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_dashboard = 1,
  anon_sym_thread = 2,
  anon_sym_jad = 3,
  anon_sym_classloader = 4,
  anon_sym_sc = 5,
  anon_sym_sm = 6,
  anon_sym_watch = 7,
  anon_sym_trace = 8,
  anon_sym_monitor = 9,
  anon_sym_tt = 10,
  anon_sym_ognl = 11,
  anon_sym_getstatic = 12,
  anon_sym_vmtool = 13,
  anon_sym_heapdump = 14,
  anon_sym_sysprop = 15,
  anon_sym_sysenv = 16,
  anon_sym_logger = 17,
  anon_sym_stop = 18,
  anon_sym_reset = 19,
  anon_sym_version = 20,
  anon_sym_help = 21,
  anon_sym_cls = 22,
  anon_sym_clear = 23,
  anon_sym_cat = 24,
  anon_sym_pwd = 25,
  anon_sym_session = 26,
  anon_sym_jobs = 27,
  anon_sym_kill = 28,
  sym_option = 29,
  sym_class_name = 30,
  sym_method_name = 31,
  sym_identifier = 32,
  sym_number = 33,
  anon_sym_DQUOTE = 34,
  aux_sym_string_token1 = 35,
  aux_sym_string_token2 = 36,
  anon_sym_SQUOTE = 37,
  aux_sym_string_token3 = 38,
  sym_ognl_expr = 39,
  sym_wildcard = 40,
  sym_comment = 41,
  sym_newline = 42,
  sym_source_file = 43,
  sym__line_content = 44,
  sym_argument = 45,
  sym_command = 46,
  sym_string = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym__line_content_repeat1 = 49,
  aux_sym_string_repeat1 = 50,
  aux_sym_string_repeat2 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_dashboard] = "dashboard",
  [anon_sym_thread] = "thread",
  [anon_sym_jad] = "jad",
  [anon_sym_classloader] = "classloader",
  [anon_sym_sc] = "sc",
  [anon_sym_sm] = "sm",
  [anon_sym_watch] = "watch",
  [anon_sym_trace] = "trace",
  [anon_sym_monitor] = "monitor",
  [anon_sym_tt] = "tt",
  [anon_sym_ognl] = "ognl",
  [anon_sym_getstatic] = "getstatic",
  [anon_sym_vmtool] = "vmtool",
  [anon_sym_heapdump] = "heapdump",
  [anon_sym_sysprop] = "sysprop",
  [anon_sym_sysenv] = "sysenv",
  [anon_sym_logger] = "logger",
  [anon_sym_stop] = "stop",
  [anon_sym_reset] = "reset",
  [anon_sym_version] = "version",
  [anon_sym_help] = "help",
  [anon_sym_cls] = "cls",
  [anon_sym_clear] = "clear",
  [anon_sym_cat] = "cat",
  [anon_sym_pwd] = "pwd",
  [anon_sym_session] = "session",
  [anon_sym_jobs] = "jobs",
  [anon_sym_kill] = "kill",
  [sym_option] = "option",
  [sym_class_name] = "class_name",
  [sym_method_name] = "method_name",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token3] = "string_token3",
  [sym_ognl_expr] = "ognl_expr",
  [sym_wildcard] = "wildcard",
  [sym_comment] = "comment",
  [sym_newline] = "newline",
  [sym_source_file] = "source_file",
  [sym__line_content] = "_line_content",
  [sym_argument] = "argument",
  [sym_command] = "command",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__line_content_repeat1] = "_line_content_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_dashboard] = anon_sym_dashboard,
  [anon_sym_thread] = anon_sym_thread,
  [anon_sym_jad] = anon_sym_jad,
  [anon_sym_classloader] = anon_sym_classloader,
  [anon_sym_sc] = anon_sym_sc,
  [anon_sym_sm] = anon_sym_sm,
  [anon_sym_watch] = anon_sym_watch,
  [anon_sym_trace] = anon_sym_trace,
  [anon_sym_monitor] = anon_sym_monitor,
  [anon_sym_tt] = anon_sym_tt,
  [anon_sym_ognl] = anon_sym_ognl,
  [anon_sym_getstatic] = anon_sym_getstatic,
  [anon_sym_vmtool] = anon_sym_vmtool,
  [anon_sym_heapdump] = anon_sym_heapdump,
  [anon_sym_sysprop] = anon_sym_sysprop,
  [anon_sym_sysenv] = anon_sym_sysenv,
  [anon_sym_logger] = anon_sym_logger,
  [anon_sym_stop] = anon_sym_stop,
  [anon_sym_reset] = anon_sym_reset,
  [anon_sym_version] = anon_sym_version,
  [anon_sym_help] = anon_sym_help,
  [anon_sym_cls] = anon_sym_cls,
  [anon_sym_clear] = anon_sym_clear,
  [anon_sym_cat] = anon_sym_cat,
  [anon_sym_pwd] = anon_sym_pwd,
  [anon_sym_session] = anon_sym_session,
  [anon_sym_jobs] = anon_sym_jobs,
  [anon_sym_kill] = anon_sym_kill,
  [sym_option] = sym_option,
  [sym_class_name] = sym_class_name,
  [sym_method_name] = sym_method_name,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token3] = aux_sym_string_token3,
  [sym_ognl_expr] = sym_ognl_expr,
  [sym_wildcard] = sym_wildcard,
  [sym_comment] = sym_comment,
  [sym_newline] = sym_newline,
  [sym_source_file] = sym_source_file,
  [sym__line_content] = sym__line_content,
  [sym_argument] = sym_argument,
  [sym_command] = sym_command,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__line_content_repeat1] = aux_sym__line_content_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_dashboard] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_thread] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jad] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_classloader] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sm] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_watch] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_trace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_monitor] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ognl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_getstatic] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_vmtool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_heapdump] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sysprop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sysenv] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_logger] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_stop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_reset] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_version] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_help] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cls] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_clear] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pwd] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_session] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jobs] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_kill] = {
    .visible = true,
    .named = false,
  },
  [sym_option] = {
    .visible = true,
    .named = true,
  },
  [sym_class_name] = {
    .visible = true,
    .named = true,
  },
  [sym_method_name] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_ognl_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_wildcard] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line_content] = {
    .visible = false,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__line_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 6,
  [9] = 5,
  [10] = 7,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 11,
  [16] = 14,
  [17] = 12,
  [18] = 13,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 22,
  [26] = 19,
  [27] = 20,
  [28] = 23,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '\n', 156,
        '"', 146,
        '\'', 150,
        '-', 3,
        '/', 4,
        '\\', 6,
        'c', 41,
        'd', 42,
        'g', 67,
        'h', 66,
        'j', 43,
        'k', 81,
        'l', 98,
        'm', 97,
        'o', 75,
        'p', 141,
        'r', 68,
        's', 55,
        't', 78,
        'v', 69,
        'w', 47,
        '{', 5,
        '*', 154,
        '?', 154,
        '$', 144,
        '.', 144,
        '_', 144,
      );
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(145);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(40);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(146);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(147);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(148);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(150);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(151);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(152);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(155);
      END_STATE();
    case 5:
      if (lookahead == '}') ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(149);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '\n', 156,
        '"', 146,
        '\'', 150,
        '-', 3,
        '/', 4,
        '{', 5,
        '*', 154,
        '?', 154,
        '$', 144,
        '.', 144,
        '_', 144,
      );
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(145);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(40);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_dashboard);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_thread);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_jad);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_classloader);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_sc);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_sm);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_watch);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_trace);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_monitor);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_tt);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_ognl);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_getstatic);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_vmtool);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_heapdump);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_sysprop);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_sysenv);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_logger);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_stop);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_reset);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_version);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_help);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_cls);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_clear);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_cat);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_pwd);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_session);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_jobs);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_kill);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_option);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_option);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_option);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_class_name);
      if (lookahead == '.') ADVANCE(143);
      if (lookahead == '$' ||
          lookahead == '-') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'a') ADVANCE(131);
      if (lookahead == 'l') ADVANCE(52);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'a') ADVANCE(121);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'a') ADVANCE(59);
      if (lookahead == 'o') ADVANCE(54);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'a') ADVANCE(112);
      if (lookahead == 'l') ADVANCE(108);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'a') ADVANCE(58);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'a') ADVANCE(113);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'a') ADVANCE(133);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'a') ADVANCE(62);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'a') ADVANCE(64);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'a') ADVANCE(134);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'a') ADVANCE(118);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'a') ADVANCE(128);
      if (lookahead == 'e') ADVANCE(46);
      if (lookahead == 's') ADVANCE(30);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'b') ADVANCE(105);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'b') ADVANCE(123);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'c') ADVANCE(13);
      if (lookahead == 'e') ADVANCE(127);
      if (lookahead == 'm') ADVANCE(14);
      if (lookahead == 't') ADVANCE(99);
      if (lookahead == 'y') ADVANCE(122);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'c') ADVANCE(20);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'c') ADVANCE(79);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'c') ADVANCE(65);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'd') ADVANCE(11);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'd') ADVANCE(33);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'd') ADVANCE(139);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'd') ADVANCE(10);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'd') ADVANCE(9);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'd') ADVANCE(74);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'e') ADVANCE(16);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'e') ADVANCE(44);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'e') ADVANCE(136);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'e') ADVANCE(129);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'e') ADVANCE(120);
      if (lookahead == 'm') ADVANCE(135);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'e') ADVANCE(92);
      if (lookahead == 'p') ADVANCE(119);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'e') ADVANCE(48);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'e') ADVANCE(114);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'e') ADVANCE(132);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'e') ADVANCE(116);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'g') ADVANCE(96);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'g') ADVANCE(77);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'g') ADVANCE(72);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'h') ADVANCE(117);
      if (lookahead == 'r') ADVANCE(45);
      if (lookahead == 't') ADVANCE(18);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'h') ADVANCE(15);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'h') ADVANCE(53);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'i') ADVANCE(89);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'i') ADVANCE(56);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'i') ADVANCE(100);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'i') ADVANCE(104);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'i') ADVANCE(137);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'l') ADVANCE(36);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'l') ADVANCE(19);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'l') ADVANCE(21);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'l') ADVANCE(86);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'l') ADVANCE(107);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'm') ADVANCE(111);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'n') ADVANCE(140);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'n') ADVANCE(34);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'n') ADVANCE(28);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'n') ADVANCE(85);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'n') ADVANCE(87);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'o') ADVANCE(95);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'o') ADVANCE(76);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'o') ADVANCE(109);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'o') ADVANCE(93);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'o') ADVANCE(110);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'o') ADVANCE(103);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'o') ADVANCE(88);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'o') ADVANCE(94);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'o') ADVANCE(51);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'o') ADVANCE(115);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'o') ADVANCE(49);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'p') ADVANCE(29);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'p') ADVANCE(26);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'p') ADVANCE(23);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'p') ADVANCE(22);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'p') ADVANCE(61);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'r') ADVANCE(31);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'r') ADVANCE(25);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'r') ADVANCE(17);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'r') ADVANCE(12);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'r') ADVANCE(71);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'r') ADVANCE(63);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'r') ADVANCE(101);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'r') ADVANCE(130);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 's') ADVANCE(80);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 's') ADVANCE(70);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 's') ADVANCE(35);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 's') ADVANCE(83);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 's') ADVANCE(90);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 's') ADVANCE(138);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 's') ADVANCE(124);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 's') ADVANCE(125);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 's') ADVANCE(73);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 's') ADVANCE(84);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 't') ADVANCE(32);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 't') ADVANCE(27);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 't') ADVANCE(57);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 't') ADVANCE(82);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 't') ADVANCE(102);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 't') ADVANCE(126);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 't') ADVANCE(106);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 't') ADVANCE(50);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'u') ADVANCE(91);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'v') ADVANCE(24);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == 'w') ADVANCE(60);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_method_name);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(145);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(147);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(148);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(148);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(aux_sym_string_token3);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(151);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(152);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(aux_sym_string_token3);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(152);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_ognl_expr);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_wildcard);
      if (lookahead == '*' ||
          lookahead == '?') ADVANCE(154);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(155);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 7},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_dashboard] = ACTIONS(1),
    [anon_sym_thread] = ACTIONS(1),
    [anon_sym_jad] = ACTIONS(1),
    [anon_sym_classloader] = ACTIONS(1),
    [anon_sym_sc] = ACTIONS(1),
    [anon_sym_sm] = ACTIONS(1),
    [anon_sym_watch] = ACTIONS(1),
    [anon_sym_trace] = ACTIONS(1),
    [anon_sym_monitor] = ACTIONS(1),
    [anon_sym_tt] = ACTIONS(1),
    [anon_sym_ognl] = ACTIONS(1),
    [anon_sym_getstatic] = ACTIONS(1),
    [anon_sym_vmtool] = ACTIONS(1),
    [anon_sym_heapdump] = ACTIONS(1),
    [anon_sym_sysprop] = ACTIONS(1),
    [anon_sym_sysenv] = ACTIONS(1),
    [anon_sym_logger] = ACTIONS(1),
    [anon_sym_stop] = ACTIONS(1),
    [anon_sym_reset] = ACTIONS(1),
    [anon_sym_version] = ACTIONS(1),
    [anon_sym_help] = ACTIONS(1),
    [anon_sym_cls] = ACTIONS(1),
    [anon_sym_clear] = ACTIONS(1),
    [anon_sym_cat] = ACTIONS(1),
    [anon_sym_pwd] = ACTIONS(1),
    [anon_sym_session] = ACTIONS(1),
    [anon_sym_jobs] = ACTIONS(1),
    [anon_sym_kill] = ACTIONS(1),
    [sym_option] = ACTIONS(1),
    [sym_class_name] = ACTIONS(1),
    [sym_method_name] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_ognl_expr] = ACTIONS(1),
    [sym_wildcard] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(33),
    [sym__line_content] = STATE(32),
    [sym_argument] = STATE(5),
    [sym_command] = STATE(5),
    [sym_string] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_dashboard] = ACTIONS(5),
    [anon_sym_thread] = ACTIONS(5),
    [anon_sym_jad] = ACTIONS(5),
    [anon_sym_classloader] = ACTIONS(5),
    [anon_sym_sc] = ACTIONS(5),
    [anon_sym_sm] = ACTIONS(5),
    [anon_sym_watch] = ACTIONS(5),
    [anon_sym_trace] = ACTIONS(5),
    [anon_sym_monitor] = ACTIONS(5),
    [anon_sym_tt] = ACTIONS(5),
    [anon_sym_ognl] = ACTIONS(5),
    [anon_sym_getstatic] = ACTIONS(5),
    [anon_sym_vmtool] = ACTIONS(5),
    [anon_sym_heapdump] = ACTIONS(5),
    [anon_sym_sysprop] = ACTIONS(5),
    [anon_sym_sysenv] = ACTIONS(5),
    [anon_sym_logger] = ACTIONS(5),
    [anon_sym_stop] = ACTIONS(5),
    [anon_sym_reset] = ACTIONS(5),
    [anon_sym_version] = ACTIONS(5),
    [anon_sym_help] = ACTIONS(5),
    [anon_sym_cls] = ACTIONS(5),
    [anon_sym_clear] = ACTIONS(5),
    [anon_sym_cat] = ACTIONS(5),
    [anon_sym_pwd] = ACTIONS(5),
    [anon_sym_session] = ACTIONS(5),
    [anon_sym_jobs] = ACTIONS(5),
    [anon_sym_kill] = ACTIONS(5),
    [sym_option] = ACTIONS(7),
    [sym_class_name] = ACTIONS(9),
    [sym_method_name] = ACTIONS(9),
    [sym_identifier] = ACTIONS(9),
    [sym_number] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_ognl_expr] = ACTIONS(7),
    [sym_wildcard] = ACTIONS(7),
    [sym_comment] = ACTIONS(15),
    [sym_newline] = ACTIONS(17),
  },
  [STATE(2)] = {
    [sym__line_content] = STATE(29),
    [sym_argument] = STATE(5),
    [sym_command] = STATE(5),
    [sym_string] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_dashboard] = ACTIONS(5),
    [anon_sym_thread] = ACTIONS(5),
    [anon_sym_jad] = ACTIONS(5),
    [anon_sym_classloader] = ACTIONS(5),
    [anon_sym_sc] = ACTIONS(5),
    [anon_sym_sm] = ACTIONS(5),
    [anon_sym_watch] = ACTIONS(5),
    [anon_sym_trace] = ACTIONS(5),
    [anon_sym_monitor] = ACTIONS(5),
    [anon_sym_tt] = ACTIONS(5),
    [anon_sym_ognl] = ACTIONS(5),
    [anon_sym_getstatic] = ACTIONS(5),
    [anon_sym_vmtool] = ACTIONS(5),
    [anon_sym_heapdump] = ACTIONS(5),
    [anon_sym_sysprop] = ACTIONS(5),
    [anon_sym_sysenv] = ACTIONS(5),
    [anon_sym_logger] = ACTIONS(5),
    [anon_sym_stop] = ACTIONS(5),
    [anon_sym_reset] = ACTIONS(5),
    [anon_sym_version] = ACTIONS(5),
    [anon_sym_help] = ACTIONS(5),
    [anon_sym_cls] = ACTIONS(5),
    [anon_sym_clear] = ACTIONS(5),
    [anon_sym_cat] = ACTIONS(5),
    [anon_sym_pwd] = ACTIONS(5),
    [anon_sym_session] = ACTIONS(5),
    [anon_sym_jobs] = ACTIONS(5),
    [anon_sym_kill] = ACTIONS(5),
    [sym_option] = ACTIONS(7),
    [sym_class_name] = ACTIONS(9),
    [sym_method_name] = ACTIONS(9),
    [sym_identifier] = ACTIONS(9),
    [sym_number] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_ognl_expr] = ACTIONS(7),
    [sym_wildcard] = ACTIONS(7),
    [sym_comment] = ACTIONS(21),
    [sym_newline] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym__line_content] = STATE(34),
    [sym_argument] = STATE(9),
    [sym_command] = STATE(9),
    [sym_string] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_dashboard] = ACTIONS(27),
    [anon_sym_thread] = ACTIONS(27),
    [anon_sym_jad] = ACTIONS(27),
    [anon_sym_classloader] = ACTIONS(27),
    [anon_sym_sc] = ACTIONS(27),
    [anon_sym_sm] = ACTIONS(27),
    [anon_sym_watch] = ACTIONS(27),
    [anon_sym_trace] = ACTIONS(27),
    [anon_sym_monitor] = ACTIONS(27),
    [anon_sym_tt] = ACTIONS(27),
    [anon_sym_ognl] = ACTIONS(27),
    [anon_sym_getstatic] = ACTIONS(27),
    [anon_sym_vmtool] = ACTIONS(27),
    [anon_sym_heapdump] = ACTIONS(27),
    [anon_sym_sysprop] = ACTIONS(27),
    [anon_sym_sysenv] = ACTIONS(27),
    [anon_sym_logger] = ACTIONS(27),
    [anon_sym_stop] = ACTIONS(27),
    [anon_sym_reset] = ACTIONS(27),
    [anon_sym_version] = ACTIONS(27),
    [anon_sym_help] = ACTIONS(27),
    [anon_sym_cls] = ACTIONS(27),
    [anon_sym_clear] = ACTIONS(27),
    [anon_sym_cat] = ACTIONS(27),
    [anon_sym_pwd] = ACTIONS(27),
    [anon_sym_session] = ACTIONS(27),
    [anon_sym_jobs] = ACTIONS(27),
    [anon_sym_kill] = ACTIONS(27),
    [sym_option] = ACTIONS(30),
    [sym_class_name] = ACTIONS(33),
    [sym_method_name] = ACTIONS(33),
    [sym_identifier] = ACTIONS(33),
    [sym_number] = ACTIONS(30),
    [anon_sym_DQUOTE] = ACTIONS(36),
    [anon_sym_SQUOTE] = ACTIONS(39),
    [sym_ognl_expr] = ACTIONS(30),
    [sym_wildcard] = ACTIONS(30),
    [sym_comment] = ACTIONS(42),
    [sym_newline] = ACTIONS(45),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_dashboard] = ACTIONS(48),
    [anon_sym_thread] = ACTIONS(48),
    [anon_sym_jad] = ACTIONS(48),
    [anon_sym_classloader] = ACTIONS(48),
    [anon_sym_sc] = ACTIONS(48),
    [anon_sym_sm] = ACTIONS(48),
    [anon_sym_watch] = ACTIONS(48),
    [anon_sym_trace] = ACTIONS(48),
    [anon_sym_monitor] = ACTIONS(48),
    [anon_sym_tt] = ACTIONS(48),
    [anon_sym_ognl] = ACTIONS(48),
    [anon_sym_getstatic] = ACTIONS(48),
    [anon_sym_vmtool] = ACTIONS(48),
    [anon_sym_heapdump] = ACTIONS(48),
    [anon_sym_sysprop] = ACTIONS(48),
    [anon_sym_sysenv] = ACTIONS(48),
    [anon_sym_logger] = ACTIONS(48),
    [anon_sym_stop] = ACTIONS(48),
    [anon_sym_reset] = ACTIONS(48),
    [anon_sym_version] = ACTIONS(48),
    [anon_sym_help] = ACTIONS(48),
    [anon_sym_cls] = ACTIONS(48),
    [anon_sym_clear] = ACTIONS(48),
    [anon_sym_cat] = ACTIONS(48),
    [anon_sym_pwd] = ACTIONS(48),
    [anon_sym_session] = ACTIONS(48),
    [anon_sym_jobs] = ACTIONS(48),
    [anon_sym_kill] = ACTIONS(48),
    [sym_option] = ACTIONS(25),
    [sym_class_name] = ACTIONS(48),
    [sym_method_name] = ACTIONS(48),
    [sym_identifier] = ACTIONS(48),
    [sym_number] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [anon_sym_SQUOTE] = ACTIONS(25),
    [sym_ognl_expr] = ACTIONS(25),
    [sym_wildcard] = ACTIONS(25),
    [sym_comment] = ACTIONS(25),
    [sym_newline] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(52), 1,
      sym_comment,
    STATE(11), 1,
      sym_string,
    ACTIONS(50), 2,
      ts_builtin_sym_end,
      sym_newline,
    STATE(6), 2,
      sym_argument,
      aux_sym__line_content_repeat1,
    ACTIONS(9), 3,
      sym_class_name,
      sym_method_name,
      sym_identifier,
    ACTIONS(7), 4,
      sym_option,
      sym_number,
      sym_ognl_expr,
      sym_wildcard,
  [32] = 8,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(56), 1,
      sym_comment,
    STATE(11), 1,
      sym_string,
    ACTIONS(54), 2,
      ts_builtin_sym_end,
      sym_newline,
    STATE(7), 2,
      sym_argument,
      aux_sym__line_content_repeat1,
    ACTIONS(9), 3,
      sym_class_name,
      sym_method_name,
      sym_identifier,
    ACTIONS(7), 4,
      sym_option,
      sym_number,
      sym_ognl_expr,
      sym_wildcard,
  [64] = 7,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_SQUOTE,
    STATE(11), 1,
      sym_string,
    STATE(7), 2,
      sym_argument,
      aux_sym__line_content_repeat1,
    ACTIONS(58), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_newline,
    ACTIONS(63), 3,
      sym_class_name,
      sym_method_name,
      sym_identifier,
    ACTIONS(60), 4,
      sym_option,
      sym_number,
      sym_ognl_expr,
      sym_wildcard,
  [94] = 8,
    ACTIONS(54), 1,
      sym_newline,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    ACTIONS(78), 1,
      anon_sym_SQUOTE,
    STATE(15), 1,
      sym_string,
    STATE(10), 2,
      sym_argument,
      aux_sym__line_content_repeat1,
    ACTIONS(74), 3,
      sym_class_name,
      sym_method_name,
      sym_identifier,
    ACTIONS(72), 4,
      sym_option,
      sym_number,
      sym_ognl_expr,
      sym_wildcard,
  [125] = 8,
    ACTIONS(50), 1,
      sym_newline,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    ACTIONS(78), 1,
      anon_sym_SQUOTE,
    STATE(15), 1,
      sym_string,
    STATE(8), 2,
      sym_argument,
      aux_sym__line_content_repeat1,
    ACTIONS(74), 3,
      sym_class_name,
      sym_method_name,
      sym_identifier,
    ACTIONS(72), 4,
      sym_option,
      sym_number,
      sym_ognl_expr,
      sym_wildcard,
  [156] = 7,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    ACTIONS(89), 1,
      anon_sym_SQUOTE,
    STATE(15), 1,
      sym_string,
    ACTIONS(58), 2,
      sym_comment,
      sym_newline,
    STATE(10), 2,
      sym_argument,
      aux_sym__line_content_repeat1,
    ACTIONS(83), 3,
      sym_class_name,
      sym_method_name,
      sym_identifier,
    ACTIONS(80), 4,
      sym_option,
      sym_number,
      sym_ognl_expr,
      sym_wildcard,
  [185] = 2,
    ACTIONS(94), 3,
      sym_class_name,
      sym_method_name,
      sym_identifier,
    ACTIONS(92), 9,
      ts_builtin_sym_end,
      sym_option,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_ognl_expr,
      sym_wildcard,
      sym_comment,
      sym_newline,
  [202] = 2,
    ACTIONS(98), 3,
      sym_class_name,
      sym_method_name,
      sym_identifier,
    ACTIONS(96), 9,
      ts_builtin_sym_end,
      sym_option,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_ognl_expr,
      sym_wildcard,
      sym_comment,
      sym_newline,
  [219] = 2,
    ACTIONS(102), 3,
      sym_class_name,
      sym_method_name,
      sym_identifier,
    ACTIONS(100), 9,
      ts_builtin_sym_end,
      sym_option,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_ognl_expr,
      sym_wildcard,
      sym_comment,
      sym_newline,
  [236] = 2,
    ACTIONS(106), 3,
      sym_class_name,
      sym_method_name,
      sym_identifier,
    ACTIONS(104), 9,
      ts_builtin_sym_end,
      sym_option,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_ognl_expr,
      sym_wildcard,
      sym_comment,
      sym_newline,
  [253] = 2,
    ACTIONS(94), 3,
      sym_class_name,
      sym_method_name,
      sym_identifier,
    ACTIONS(92), 8,
      sym_option,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_ognl_expr,
      sym_wildcard,
      sym_comment,
      sym_newline,
  [269] = 2,
    ACTIONS(106), 3,
      sym_class_name,
      sym_method_name,
      sym_identifier,
    ACTIONS(104), 8,
      sym_option,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_ognl_expr,
      sym_wildcard,
      sym_comment,
      sym_newline,
  [285] = 2,
    ACTIONS(98), 3,
      sym_class_name,
      sym_method_name,
      sym_identifier,
    ACTIONS(96), 8,
      sym_option,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_ognl_expr,
      sym_wildcard,
      sym_comment,
      sym_newline,
  [301] = 2,
    ACTIONS(102), 3,
      sym_class_name,
      sym_method_name,
      sym_identifier,
    ACTIONS(100), 8,
      sym_option,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_ognl_expr,
      sym_wildcard,
      sym_comment,
      sym_newline,
  [317] = 4,
    ACTIONS(108), 1,
      aux_sym_string_token2,
    ACTIONS(110), 1,
      anon_sym_SQUOTE,
    ACTIONS(112), 1,
      aux_sym_string_token3,
    STATE(21), 1,
      aux_sym_string_repeat2,
  [330] = 4,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    ACTIONS(116), 1,
      aux_sym_string_token1,
    ACTIONS(118), 1,
      aux_sym_string_token2,
    STATE(23), 1,
      aux_sym_string_repeat1,
  [343] = 4,
    ACTIONS(120), 1,
      aux_sym_string_token2,
    ACTIONS(123), 1,
      anon_sym_SQUOTE,
    ACTIONS(125), 1,
      aux_sym_string_token3,
    STATE(21), 1,
      aux_sym_string_repeat2,
  [356] = 4,
    ACTIONS(114), 1,
      anon_sym_SQUOTE,
    ACTIONS(128), 1,
      aux_sym_string_token2,
    ACTIONS(130), 1,
      aux_sym_string_token3,
    STATE(19), 1,
      aux_sym_string_repeat2,
  [369] = 4,
    ACTIONS(110), 1,
      anon_sym_DQUOTE,
    ACTIONS(132), 1,
      aux_sym_string_token1,
    ACTIONS(134), 1,
      aux_sym_string_token2,
    STATE(24), 1,
      aux_sym_string_repeat1,
  [382] = 4,
    ACTIONS(136), 1,
      anon_sym_DQUOTE,
    ACTIONS(138), 1,
      aux_sym_string_token1,
    ACTIONS(141), 1,
      aux_sym_string_token2,
    STATE(24), 1,
      aux_sym_string_repeat1,
  [395] = 4,
    ACTIONS(144), 1,
      aux_sym_string_token2,
    ACTIONS(146), 1,
      anon_sym_SQUOTE,
    ACTIONS(148), 1,
      aux_sym_string_token3,
    STATE(26), 1,
      aux_sym_string_repeat2,
  [408] = 4,
    ACTIONS(108), 1,
      aux_sym_string_token2,
    ACTIONS(112), 1,
      aux_sym_string_token3,
    ACTIONS(150), 1,
      anon_sym_SQUOTE,
    STATE(21), 1,
      aux_sym_string_repeat2,
  [421] = 4,
    ACTIONS(146), 1,
      anon_sym_DQUOTE,
    ACTIONS(152), 1,
      aux_sym_string_token1,
    ACTIONS(154), 1,
      aux_sym_string_token2,
    STATE(28), 1,
      aux_sym_string_repeat1,
  [434] = 4,
    ACTIONS(132), 1,
      aux_sym_string_token1,
    ACTIONS(134), 1,
      aux_sym_string_token2,
    ACTIONS(150), 1,
      anon_sym_DQUOTE,
    STATE(24), 1,
      aux_sym_string_repeat1,
  [447] = 2,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
    ACTIONS(158), 1,
      sym_newline,
  [454] = 1,
    ACTIONS(160), 2,
      ts_builtin_sym_end,
      sym_newline,
  [459] = 1,
    ACTIONS(54), 2,
      ts_builtin_sym_end,
      sym_newline,
  [464] = 2,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(158), 1,
      sym_newline,
  [471] = 1,
    ACTIONS(162), 1,
      ts_builtin_sym_end,
  [475] = 1,
    ACTIONS(158), 1,
      sym_newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 32,
  [SMALL_STATE(7)] = 64,
  [SMALL_STATE(8)] = 94,
  [SMALL_STATE(9)] = 125,
  [SMALL_STATE(10)] = 156,
  [SMALL_STATE(11)] = 185,
  [SMALL_STATE(12)] = 202,
  [SMALL_STATE(13)] = 219,
  [SMALL_STATE(14)] = 236,
  [SMALL_STATE(15)] = 253,
  [SMALL_STATE(16)] = 269,
  [SMALL_STATE(17)] = 285,
  [SMALL_STATE(18)] = 301,
  [SMALL_STATE(19)] = 317,
  [SMALL_STATE(20)] = 330,
  [SMALL_STATE(21)] = 343,
  [SMALL_STATE(22)] = 356,
  [SMALL_STATE(23)] = 369,
  [SMALL_STATE(24)] = 382,
  [SMALL_STATE(25)] = 395,
  [SMALL_STATE(26)] = 408,
  [SMALL_STATE(27)] = 421,
  [SMALL_STATE(28)] = 434,
  [SMALL_STATE(29)] = 447,
  [SMALL_STATE(30)] = 454,
  [SMALL_STATE(31)] = 459,
  [SMALL_STATE(32)] = 464,
  [SMALL_STATE(33)] = 471,
  [SMALL_STATE(34)] = 475,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line_content, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line_content, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__line_content_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__line_content_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__line_content_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__line_content_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__line_content_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__line_content_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__line_content_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__line_content_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__line_content_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [120] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0), SHIFT_REPEAT(21),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0), SHIFT_REPEAT(21),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [141] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line_content, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_arthas(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
