# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

env = XMODIFIERS,@im=fcitx
env = QT_IM_MODULE,fcitx
env = SDL_IM_MODULE,fcitx

exec-once = fcitx5 -d
exec-once = waybar
exec-once = swaybg -i ~/4.png -m fill

input {
    kb_options = caps:escape
}

$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, G, exec, flatpak run com.google.Chrome
bind = $mainMod, N, exec, workspace, empty
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, LEFT, workspace, e-1    # 前一个
bind = $mainMod, RIGHT, workspace, e+1   # 后一个

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
