# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

env = XMODIFIERS,@im=fcitx
env = QT_IM_MODULE,fcitx
env = SDL_IM_MODULE,fcitx
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

xwayland {
    force_zero_scaling = true
}

input {
    sensitivity = 0.5 # 灵敏度设置
    accel_profile = flat # 禁用鼠标硬件加速，让鼠标移动更精准
}

exec-once = fcitx5 -d
exec-once = waybar
exec-once = swaybg -i ~/4.png -m fill

monitor = , preferred, auto, 1.67

general {
    gaps_in = 2
    gaps_out = 2
    border_size = 1
}

decoration {
    rounding = 8

    # blur {
    #     enabled = true
    #     size = 8
    #     passes = 3
    #     noise = 0.02
    #     vibrancy = 0.2
    # }
}

# layerrule = blur, waybar
# layerrule = ignorealpha 0.3, waybar

input {
    kb_options = caps:escape
}

$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, F, fullscreen, 0
bind = $mainMod, R, exec, $menu
bind = $mainMod, G, exec, flatpak run com.google.Chrome
bind = $mainMod, N, workspace, empty
bind = $mainMod SHIFT, N, movetoworkspace, empty
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod, LEFT, workspace, e-1    # 前一个
bind = $mainMod, RIGHT, workspace, e+1   # 后一个
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

bind = ALT, TAB, cyclenext,
bind = ALT SHIFT, TAB, cyclenext, prev

# 上下窗口平均分割
bind = $mainMod, equal, layoutmsg, splitratio 1.0 exact
# 左右窗口平均分割
bind = $mainMod SHIFT, 5, layoutmsg, splitratio 1.0 exact

# 左键
bindm = $mainMod, mouse:272, movewindow
# 右键
bindm = $mainMod, mouse:273, resizewindow
